env:
  browser: true
  es2021: true
extends:
  - 'react-app'
  - 'react-app/jest'
  - 'plugin:react/recommended'
  - 'airbnb'
  - 'airbnb-typescript'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  project: ./tsconfig.json
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - import
root: true
